// Frontload gate plugin for opencode.
// Generated by Frontload. Keep this wrapper thin; gate behavior lives in
// dist/src/gate/adapters/opencode.js.

import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const preferredAdapterUrl = null;
const adapterRelativePath = "dist/src/gate/adapters/opencode.js";

function executableNames(command) {
  if (process.platform !== "win32") return [command];
  const extensions = (process.env.PATHEXT ?? ".EXE;.CMD;.BAT;.COM").split(";").filter(Boolean);
  return extensions.flatMap((ext) => [command + ext.toLowerCase(), command + ext.toUpperCase()]).concat(command);
}

function frontloadExecutables() {
  const found = [];
  for (const dir of (process.env.PATH ?? "").split(path.delimiter).filter(Boolean)) {
    for (const name of executableNames("frontload")) {
      const candidate = path.join(dir, name);
      try {
        fs.accessSync(candidate, fs.constants.X_OK);
        found.push(candidate);
      } catch {
        // Keep looking through PATH.
      }
    }
  }
  return found;
}

function packageRootFrom(start) {
  let dir = path.resolve(start);
  try {
    if (fs.statSync(dir).isFile()) dir = path.dirname(fs.realpathSync(dir));
  } catch {
    return null;
  }
  while (dir !== path.dirname(dir)) {
    const pkg = path.join(dir, "package.json");
    if (fs.existsSync(pkg)) {
      try {
        const parsed = JSON.parse(fs.readFileSync(pkg, "utf8"));
        if (parsed.name === "frontload") return dir;
      } catch {
        // Keep walking upward.
      }
    }
    dir = path.dirname(dir);
  }
  return null;
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}

function adapterCandidates() {
  const packageRoots = frontloadExecutables().map(packageRootFrom);
  return unique([
    preferredAdapterUrl,
    ...packageRoots.map((root) => root ? pathToFileURL(path.join(root, adapterRelativePath)).href : null),
    "frontload/" + adapterRelativePath
  ]);
}

async function loadAdapter() {
  for (const candidate of adapterCandidates()) {
    try {
      const adapter = await import(candidate);
      if (typeof adapter.FrontloadGate === "function") return adapter;
    } catch {
      // Fail open if this candidate is unavailable in the host environment.
    }
  }
  return null;
}

export const FrontloadGate = async (context) => {
  const adapter = await loadAdapter();
  return adapter ? adapter.FrontloadGate(context) : {};
};
